name: CI

# ↓ lock down top-level permissions. Define all permissions at job level
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group:
    ${{ github.event_name != 'merge_group' && format('{0}-{1}', github.workflow, github.head_ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read             # we only need to checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Setup Compact compiler
        uses: midnightntwrk/setup-compact-action@836895c8fffbbea6bd986af2b17e8941ff29d1f8
        with:
          compact-version: '0.31.0'

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6.3.0
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Compile contracts
        run: yarn compact

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test
